cookie:
  expiry_days: 30
  key: cookie_signature_key
  name: unique_key
credentials:
  usernames:
    user1:
      email: user1@gmail.com
      logged_in: false
      name: User 1
      password: $2b$12$D/oIsuODfN04LYo4nUsV3ORC2Ek2/G/Lu3fVJBJY0zj1r8U21TP9S
    user2:
      email: user2@gmail.com
      logged_in: false
      name: User 2
      password: $2b$12$D/oIsuODfN04LYo4nUsV3ORC2Ek2/G/Lu3fVJBJY0zj1r8U21TP9S
preauthorized:
  emails:
  - venkat09docs@gmail.com
